#!/data/data/com.termux/files/usr/bin/bash
# ops/vps-setup.sh — provision the far end for INGRESS_MODE=vps-tunnel.
#
#   bash scripts/ops/vps-setup.sh root@<host>        # provision
#   bash scripts/ops/vps-setup.sh root@<host> --check # print, change nothing
#
# Run this from the phone. It needs ROOT ssh to the VPS once; after that the
# phone only ever logs in as the unprivileged tunnel user.
#
# What it sets up, and why each part is load-bearing:
#
#   Caddy            terminates public TLS and proxies into the reverse forward.
#                    Certificates come from Let's Encrypt over HTTP-01, so the
#                    hostnames must already resolve to this box.
#   tunnel user      nologin shell, locked password, and an authorized_keys entry
#                    of `restrict,port-forwarding`. `restrict` disables pty,
#                    agent/X11 forwarding and user rc; only forwarding is added
#                    back. That key cannot get a shell even if it tries.
#   GatewayPorts no  (the default, asserted here) keeps the -R endpoint on the
#                    VPS's own loopback, so the phone's Caddy is never exposed
#                    directly to the internet.
#   ClientAlive*     NOT optional. When the phone's link drops silently the old
#                    session keeps holding 127.0.0.1:<port> and every reconnect
#                    fails with "remote port forwarding failed for listen port".
#                    Probing reaps the dead session in ~90s. We hit this for real.
#
# The apex block is served statically rather than proxied: MATRIX_SERVER_NAME is
# the apex, so Matrix clients run .well-known discovery against it — and that
# must keep answering even while the phone is offline.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "${HERE}/../lib/common.sh"
load_env

TARGET="${1:-}"
CHECK=0
[ "${2:-}" = "--check" ] && CHECK=1
[ -n "${TARGET}" ] || die "usage: $(basename "$0") root@<vps-host> [--check]"

require_var DOMAIN   "your apex domain"
require_var VPS_HOST "the VPS that terminates TLS"
VPS_USER="${VPS_USER:-tunnel}"
PORT="${CADDY_PORT:-8443}"
KEY="${VPS_TUNNEL_KEY:-${HOME}/.ssh/pocket-tunnel_ed25519}"

[ -f "${KEY}.pub" ] || die "no tunnel public key at ${KEY}.pub — run scripts/install.sh first"
PUBKEY="$(cat "${KEY}.pub")"

# ── Which hostnames does this deployment actually publish? ──────────────────
# Generated from the ENABLE_* flags so the vhost list cannot drift from reality.
HOSTS="chat.${DOMAIN}"
[ "${ENABLE_ADMIN:-true}"     = "true" ] && HOSTS="${HOSTS},admin.${DOMAIN}"
[ "${ENABLE_DUFS:-false}"     = "true" ] && HOSTS="${HOSTS},files.${DOMAIN}"
[ "${ENABLE_FILEBROWSER:-false}" = "true" ] && HOSTS="${HOSTS},files.${DOMAIN}"
[ "${ENABLE_NAVIDROME:-false}" = "true" ] && HOSTS="${HOSTS},music.${DOMAIN}"
[ "${ENABLE_KAVITA:-false}"   = "true" ] && HOSTS="${HOSTS},books.${DOMAIN}"
[ "${ENABLE_AUDIOBOOKSHELF:-false}" = "true" ] && HOSTS="${HOSTS},audiobooks.${DOMAIN}"
[ "${ENABLE_LINKDING:-false}" = "true" ] && HOSTS="${HOSTS},links.${DOMAIN}"
[ "${ENABLE_FRESHRSS:-false}" = "true" ] && HOSTS="${HOSTS},rss.${DOMAIN}"
[ "${ENABLE_MEMOS:-false}"    = "true" ] && HOSTS="${HOSTS},notes.${DOMAIN}"
[ "${ENABLE_VIKUNJA:-false}"  = "true" ] && HOSTS="${HOSTS},tasks.${DOMAIN}"
[ "${ENABLE_FORGEJO:-false}"  = "true" ] && HOSTS="${HOSTS},git.${DOMAIN}"
# de-duplicate (dufs + filebrowser both claim files.)
HOSTS="$(printf '%s' "${HOSTS}" | tr ',' '\n' | awk '!seen[$0]++' | paste -sd, -)"

# POCKET_HOSTS_ONELINE: Caddy accepts several site addresses on one line
# separated by ", ". Building that here avoids sed escaping inside the heredoc,
# which silently produced an EMPTY site block (and a config that would have
# matched nothing).
HOSTS_LIST="$(printf '%s' "${HOSTS}" | sed 's/,/, /g')"

CADDYFILE="$(cat <<CADDY
# Generated by pocket-homeserver scripts/ops/vps-setup.sh — do not hand-edit.
# The phone serves plain HTTP on its own loopback:${PORT}; an outbound \`ssh -R\`
# lands that listener on THIS box's 127.0.0.1:${PORT}. This file is the only
# thing terminating public TLS.

{
	admin off
}

# The apex: MATRIX_SERVER_NAME is the apex, so clients run .well-known discovery
# here rather than against chat.*. Served STATICALLY so discovery keeps working
# even when the phone is offline — and so the apex has a certificate at all
# (without a block here the TLS handshake fails with an internal-error alert).
${DOMAIN} {
	encode zstd gzip
	handle /.well-known/matrix/client {
		header Content-Type application/json
		header Access-Control-Allow-Origin *
		respond \`{"m.homeserver":{"base_url":"https://chat.${DOMAIN}"}}\` 200
	}
	handle /.well-known/matrix/server {
		header Content-Type application/json
		respond \`{"m.server":"chat.${DOMAIN}:443"}\` 200
	}
	handle {
		redir https://chat.${DOMAIN}{uri} 302
	}
}

${HOSTS_LIST} {
	encode zstd gzip
	reverse_proxy 127.0.0.1:${PORT} {
		# The phone's Caddyfile reads the real client IP from Cf-Connecting-IP
		# (it was written for a Cloudflare Tunnel). Setting the same header here
		# keeps its access log honest with no edit to the upstream template.
		header_up Cf-Connecting-IP {remote_host}
		header_up X-Forwarded-For {remote_host}
		header_up X-Forwarded-Proto {scheme}
		transport http {
			dial_timeout 10s
			response_header_timeout 600s
		}
	}
	# POCKET_NO_BODY_CAP: NO request_body cap here.
	# A cap rejects an upload with 413 only AFTER the client has streamed the
	# whole file, which Windows' WebDAV client shows as a generic hang at 100%
	# rather than an error. A 200MB cap silently killed 33 uploads of a mod pack
	# before anyone traced it. Matrix media has its own limit inside conduwuit;
	# the edge does not need to guess one on the file server's behalf.
	log {
		output file /var/log/caddy/pocket-access.log {
			roll_size 10MiB
			roll_keep 5
		}
		format json
	}
}
CADDY
)"

REMOTE="$(cat <<REMOTE_SCRIPT
set -e
export DEBIAN_FRONTEND=noninteractive

echo "== Caddy =="
if ! command -v caddy >/dev/null 2>&1; then
  apt-get update -qq
  apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl gpg >/dev/null
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' > /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -qq
  apt-get install -y -qq caddy
fi
caddy version | head -1

echo "== tunnel user =="
id ${VPS_USER} >/dev/null 2>&1 || { useradd --create-home --shell /usr/sbin/nologin ${VPS_USER}; passwd --lock ${VPS_USER} >/dev/null; }
install -d -m 700 -o ${VPS_USER} -g ${VPS_USER} /home/${VPS_USER}/.ssh
touch /home/${VPS_USER}/.ssh/authorized_keys
grep -qF '${PUBKEY##* }' /home/${VPS_USER}/.ssh/authorized_keys 2>/dev/null \
  || echo 'restrict,port-forwarding ${PUBKEY}' >> /home/${VPS_USER}/.ssh/authorized_keys
chown ${VPS_USER}:${VPS_USER} /home/${VPS_USER}/.ssh/authorized_keys
chmod 600 /home/${VPS_USER}/.ssh/authorized_keys
echo "authorized_keys entries: \$(wc -l < /home/${VPS_USER}/.ssh/authorized_keys)"

echo "== sshd: reap dead tunnels =="
if ! grep -rq POCKET_TUNNEL_KEEPALIVE /etc/ssh/sshd_config.d/ 2>/dev/null; then
  cat > /etc/ssh/sshd_config.d/99-pocket-tunnel.conf <<'CONF'
# POCKET_TUNNEL_KEEPALIVE
# A silently dropped phone link leaves the old session holding the forwarded
# port; every reconnect then fails with "remote port forwarding failed" until
# someone kills it by hand. Probe so a dead client is reaped in ~90s.
ClientAliveInterval 30
ClientAliveCountMax 3
CONF
fi
sshd -t && systemctl reload ssh 2>/dev/null || systemctl reload sshd 2>/dev/null || true
sshd -T | grep -E '^(gatewayports|allowtcpforwarding|clientaliveinterval)'

echo "== Caddyfile =="
mkdir -p /var/log/caddy && chown -R caddy:caddy /var/log/caddy
# The config was uploaded separately (see the scp below). Reading it from stdin
# here would fight with \`bash -s\`, which is already consuming stdin.
test -s /tmp/pocket-Caddyfile || { echo "uploaded Caddyfile missing"; exit 1; }
caddy validate --config /tmp/pocket-Caddyfile --adapter caddyfile >/dev/null 2>&1 \
  || { echo "GENERATED CADDYFILE IS INVALID — not installing"; exit 1; }
install -m 644 /tmp/pocket-Caddyfile /etc/caddy/Caddyfile
rm -f /tmp/pocket-Caddyfile
chown caddy:caddy /etc/caddy/Caddyfile
systemctl enable caddy >/dev/null 2>&1 || true
systemctl restart caddy
sleep 5
systemctl is-active caddy
echo "VPS_SETUP_DONE"
REMOTE_SCRIPT
)"

say "target      : ${TARGET}"
say "tunnel user : ${VPS_USER}"
say "hostnames   : ${HOSTS}"
say "forward     : ${TARGET%%@*} 127.0.0.1:${PORT} -> phone 127.0.0.1:${PORT}"

if [ "${CHECK}" -eq 1 ]; then
  echo
  echo "--- Caddyfile that WOULD be installed ---"
  printf '%s\n' "${CADDYFILE}"
  echo "--- (no changes made) ---"
  exit 0
fi

warn "DNS must already point these hostnames at ${VPS_HOST} — Let's Encrypt"
warn "validates over HTTP-01, and a failed attempt counts against rate limits."

TMP="$(mktemp)"
printf '%s\n' "${CADDYFILE}" > "${TMP}"
trap 'rm -f "${TMP}"' EXIT

say "uploading the generated Caddyfile"
scp -o ConnectTimeout=20 "${TMP}" "${TARGET}:/tmp/pocket-Caddyfile" >/dev/null \
  || die "could not upload the Caddyfile to ${TARGET}"

say "provisioning ${TARGET} (you will be asked for its credentials once)"
ssh -o ConnectTimeout=30 "${TARGET}" "bash -s" <<< "${REMOTE}" \
  || die "remote provisioning failed"

ok "VPS provisioned"
say "next: ${POCKET_ROOT}/scripts/install.sh   (brings the tunnel up from this end)"
